services:
  arma-reforger:
    image: ghcr.io/acemod/arma-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger-server
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp"  # RCON
    volumes:
      - ./reforger/configs:/reforger/Configs
      - ./reforger/workshop:/reforger/workshop
      - ./reforger:/home/profile
    environment:
      - ARMA_CONFIG=coe2_mogadishu.json
      - ARMA_MAX_FPS=60
      - ARMA_PARAMS=-autoreload 10 -loadSessionSave
